image: docker/compose:latest
services:
  - docker:dind
stages:
  # - build
  # - test
  - deploy
default:
  before_script:
    - ./deploy/env.sh
    - cp ./deploy/docker-compose.yml.example ./deploy/docker-compose.yml
    - docker info
    - docker-compose --version

# test:
#   stage: test
#   only:
#     - dev
#   script:
#     - echo running tests in test

deploy-dev:
  stage: deploy
  only:
    - develop
  script:
    - cd ./deploy;
    - docker-compose up --build -d

deploy-trial:
  stage: deploy
  only:
    - trial
  script:
    - echo NEXT_PUBLIC_GRAPHQL_URL=$NEXT_PUBLIC_GRAPHQL_URL_TRIAL >> .env
    - echo NEXT_PUBLIC_GRAPHQL_SUBSCRIPTION_URL=$NEXT_PUBLIC_GRAPHQL_SUBSCRIPTION_URL_TRIAL >> .env
    - docker build -t tournament_fe_trial:$CI_COMMIT_SHORT_SHA -f deploy/Dockerfile .
    - docker stop tournament_fe_trial || true
    - docker rm tournament_fe_trial || true
    - docker run -p 3001:3000 --restart always --network lucis_network --name tournament_fe_trial -d tournament_fe_trial:$CI_COMMIT_SHORT_SHA
