image: docker/compose:latest
services:
  - docker:dind
stages:
  # - build
  # - test
  - deploy
default:
  before_script:
    - cp ./deploy/docker-compose.yml.example ./deploy/docker-compose.yml
    - docker info
    - docker-compose --version

# test:
#   stage: test
#   only:
#     - dev
#   script:
#     - echo running tests in test

deploy-dev:
  stage: deploy
  only:
    - develop
  script:
    - echo NEXT_PUBLIC_GRAPHQL_URL=$NEXT_PUBLIC_GRAPHQL_URL >> .env
    - echo NEXT_PUBLIC_GRAPHQL_SUBSCRIPTION_URL=$NEXT_PUBLIC_GRAPHQL_SUBSCRIPTION_URL_TRIAL >> .env
    - echo NEXT_PUBLIC_GRAPHQL_P2E_URL=$NEXT_PUBLIC_GRAPHQL_P2E_URL >> .env
    - echo NEXT_PUBLIC_GOOGLE_ID=$NEXT_PUBLIC_GOOGLE_ID >> .env
    - echo NEXT_PUBLIC_FACEBOOK_ID=$NEXT_PUBLIC_FACEBOOK_ID >> .env
    - echo NEXT_PUBLIC_CHAIN_ID__ETH=$NEXT_PUBLIC_CHAIN_ID__ETH >> .env
    - echo NEXT_PUBLIC_CHAIN_ID__BSC=$NEXT_PUBLIC_CHAIN_ID__BSC >> .env
    - echo NEXT_PUBLIC_CHAIN_ID__POLYGON=$NEXT_PUBLIC_CHAIN_ID__POLYGON >> .env
    - echo NEXT_PUBLIC_BUCKET_NAME=$NEXT_PUBLIC_BUCKET_NAME >> .env
    - echo NEXT_PUBLIC_REGION=$NEXT_PUBLIC_REGION >> .env
    - echo NEXT_PUBLIC_ACCESS_KEY=$NEXT_PUBLIC_ACCESS_KEY >> .env
    - echo NEXT_PUBLIC_SECRET_ACCESS_KEY=$NEXT_PUBLIC_SECRET_ACCESS_KEY >> .env
    - echo NEXT_PUBLIC_FACEIT_CLIENT_ID_TEST=$NEXT_PUBLIC_FACEIT_CLIENT_ID_TEST >> .env
    - echo NEXT_PUBLIC_FACEIT_CLIENT_ID_DEV=$NEXT_PUBLIC_FACEIT_CLIENT_ID_DEV >> .env
    - cd ./deploy;
    - docker-compose up --build -d

deploy-trial:
  stage: deploy
  only:
    - trial
  script:
    - echo NEXT_PUBLIC_GRAPHQL_URL=$NEXT_PUBLIC_GRAPHQL_URL_TRIAL >> .env
    - echo NEXT_PUBLIC_GRAPHQL_SUBSCRIPTION_URL=$NEXT_PUBLIC_GRAPHQL_SUBSCRIPTION_URL_TRIAL >> .env
    - docker build -t tournament_fe_trial:$CI_COMMIT_SHORT_SHA -f deploy/Dockerfile .
    - docker stop tournament_fe_trial || true
    - docker rm tournament_fe_trial || true
    - docker run -p 3001:3000 --restart always --network lucis_network --name tournament_fe_trial -d tournament_fe_trial:$CI_COMMIT_SHORT_SHA
