version: '3'

services:
  playcore_fe_isr:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: playcore_fe
    container_name: "playcore_fe_isr"
    ports:
      - '15001:3000'
