# name: Create Trello card on opened issues

# on:
#   issues:
#     types: [opened, reopened]

# jobs:
#   create_trello_card_job:
#     runs-on: ubuntu-latest
#     name: Create Trello Card
#     steps:
#       - name: Call trello-github-actions
#         uses: Yleisradio/github-action-trello-integration@v1.1.0
#         with:
#           action: issue_opened_create_card
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
#           TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}
#           # TRELLO_BOARD_ID must match a board. GH repo should connect
#           # to exactly one board, but Trello board may connect to multiple
#           # GH repositories.
#           TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }} # BOARD-24-CHAR-LONG-ID
#           # Backlog list ID
#           TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }} # LIST-24-CHAR-LONG-ID
